// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {config} from '../models';

export function EmitScraperData(arg1:Array<models.Data>):Promise<void>;

export function EmitScraperError(arg1:string):Promise<void>;

export function EmitScraperState(arg1:string):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function Greet(arg1:string):Promise<string>;

export function UpdateConfig(arg1:config.Config):Promise<void>;
