// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utils} from '../models';
import {models} from '../models';
import {config} from '../models';

export function EmitLog(arg1:utils.LogEntry):Promise<void>;

export function EmitScraperData(arg1:Array<models.Data>,arg2:Array<models.Data>):Promise<void>;

export function EmitScraperError(arg1:string):Promise<void>;

export function EmitScraperState(arg1:string):Promise<void>;

export function EmitURLStatus(arg1:Array<models.URLStatus>):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function IsScraperRunning():Promise<boolean>;

export function PreviewScrape():Promise<models.PreviewResult>;

export function PreviewURL(arg1:string):Promise<Array<models.Data>>;

export function RequestScraperStop():Promise<void>;

export function StartScraper():Promise<void>;

export function StopScraper():Promise<void>;

export function UpdateConfig(arg1:config.Config):Promise<void>;
