// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EmitLog(arg1) {
  return window['go']['main']['App']['EmitLog'](arg1);
}

export function EmitScraperData(arg1, arg2) {
  return window['go']['main']['App']['EmitScraperData'](arg1, arg2);
}

export function EmitScraperError(arg1) {
  return window['go']['main']['App']['EmitScraperError'](arg1);
}

export function EmitScraperState(arg1) {
  return window['go']['main']['App']['EmitScraperState'](arg1);
}

export function EmitURLStatus(arg1) {
  return window['go']['main']['App']['EmitURLStatus'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsScraperRunning() {
  return window['go']['main']['App']['IsScraperRunning']();
}

export function PreviewScrape() {
  return window['go']['main']['App']['PreviewScrape']();
}

export function PreviewURL(arg1) {
  return window['go']['main']['App']['PreviewURL'](arg1);
}

export function RequestScraperStop() {
  return window['go']['main']['App']['RequestScraperStop']();
}

export function StartScraper() {
  return window['go']['main']['App']['StartScraper']();
}

export function StopScraper() {
  return window['go']['main']['App']['StopScraper']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
